
import './globals.css'
import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import LayoutHome from '@/layouts/LayoutHome'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json'
}

const inter = Manrope({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="app">
          <LayoutHome>
          {children}
          </LayoutHome>
        </div>
      </body>
    </html>
  )
}
